spring.application.name=secure-api-demo

# remove the spring banner 
spring.main.banner-mode=off

#
# configure the postgres jdbc
#
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# configure spring security credentials 
spring.security.user.name=admin
spring.security.user.password=pass